//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biit_Employee_Performance_Apraisal_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassHeldReport
    {
        public int id { get; set; }
        public string course { get; set; }
        public string teacher { get; set; }
        public string discipline { get; set; }
        public string venue { get; set; }
        public string status { get; set; }
        public string session { get; set; }
        public Nullable<int> late_in { get; set; }
        public Nullable<int> left_early { get; set; }
        public string remarks { get; set; }
    }
}
