//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biit_Employee_Performance_Apraisal_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_KPI_WEIGHTAGE
    {
        public int SUB_KPI_ID { get; set; }
        public int SessionID { get; set; }
        public int Weightage { get; set; }
    
        public virtual SESSION SESSION { get; set; }
        public virtual SUB_KPI SUB_KPI { get; set; }
    }
}
