//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biit_Employee_Performance_Apraisal_API
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        public int TaskID { get; set; }
        public int AssignedToID { get; set; }
        public int AssignedByID { get; set; }
        public string TaskDescription { get; set; }
        public int Status { get; set; }
        public int Weightage { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.Int32> Score { get; set; }

        [JsonIgnore]
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [JsonIgnore]
        public virtual EMPLOYEE EMPLOYEE1 { get; set; }
    }
}
