//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biit_Employee_Performance_Apraisal_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class GroupKpi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupKpi()
        {
            this.KpiWeightages = new HashSet<KpiWeightage>();
        }
    
        public int id { get; set; }
        public int kpi_id { get; set; }
        public Nullable<int> designation_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> employee_type_id { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        [JsonIgnore] public virtual Department Department { get; set; }
        [JsonIgnore] public virtual Designation Designation { get; set; }
        [JsonIgnore] public virtual Employee Employee { get; set; }
        [JsonIgnore] public virtual EmployeeType EmployeeType { get; set; }
        [JsonIgnore] public virtual Kpi Kpi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore] public virtual ICollection<KpiWeightage> KpiWeightages { get; set; }
    }
}
