//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biit_Employee_Performance_Apraisal_API.Models
{
    using System; using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class GroupKpi
    {
        public int id { get; set; }
        public int kpi_id { get; set; }
        public Nullable<int> designation_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> employee_type_id { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        [JsonIgnore] public virtual Department Department { get; set; }
        [JsonIgnore] public virtual Designation Designation { get; set; }
        [JsonIgnore] public virtual Employee Employee { get; set; }
        [JsonIgnore] public virtual EmployeeType EmployeeType { get; set; }
        [JsonIgnore] public virtual Kpi Kpi { get; set; }
    }
}
