//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biit_Employee_Performance_Apraisal_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Biit_Employee_Performance_AppraisalEntities : DbContext
    {
        public Biit_Employee_Performance_AppraisalEntities()
            : base("name=Biit_Employee_Performance_AppraisalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        [JsonIgnore] public virtual DbSet<ClassHeldReport> ClassHeldReports { get; set; }
        [JsonIgnore] public virtual DbSet<Course> Courses { get; set; }
        [JsonIgnore] public virtual DbSet<Department> Departments { get; set; }
        [JsonIgnore] public virtual DbSet<Designation> Designations { get; set; }
        [JsonIgnore] public virtual DbSet<Employee> Employees { get; set; }
        [JsonIgnore] public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        [JsonIgnore] public virtual DbSet<Enrollment> Enrollments { get; set; }
        [JsonIgnore] public virtual DbSet<EvaluationPin> EvaluationPins { get; set; }
        [JsonIgnore] public virtual DbSet<EvaluationTime> EvaluationTimes { get; set; }
        [JsonIgnore] public virtual DbSet<Evaluator> Evaluators { get; set; }
        [JsonIgnore] public virtual DbSet<Kpi> Kpis { get; set; }
        [JsonIgnore] public virtual DbSet<KpiEmployeeScore> KpiEmployeeScores { get; set; }
        [JsonIgnore] public virtual DbSet<OptionsWeightage> OptionsWeightages { get; set; }
        [JsonIgnore] public virtual DbSet<PeerEvaluation> PeerEvaluations { get; set; }
        [JsonIgnore] public virtual DbSet<Questionaire> Questionaires { get; set; }
        [JsonIgnore] public virtual DbSet<QuestionaireType> QuestionaireTypes { get; set; }
        [JsonIgnore] public virtual DbSet<Session> Sessions { get; set; }
        [JsonIgnore] public virtual DbSet<Student> Students { get; set; }
        [JsonIgnore] public virtual DbSet<StudentEvaluation> StudentEvaluations { get; set; }
        [JsonIgnore] public virtual DbSet<SubKpi> SubKpis { get; set; }
        [JsonIgnore] public virtual DbSet<SubkpiEmployeeScore> SubkpiEmployeeScores { get; set; }
        [JsonIgnore] public virtual DbSet<SubKpiWeightage> SubKpiWeightages { get; set; }
        [JsonIgnore] public virtual DbSet<SupervisorEvaluation> SupervisorEvaluations { get; set; }
        [JsonIgnore] public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        [JsonIgnore] public virtual DbSet<Task> Tasks { get; set; }
        [JsonIgnore] public virtual DbSet<TeacherJunior> TeacherJuniors { get; set; }
        [JsonIgnore] public virtual DbSet<GroupKpi> GroupKpis { get; set; }
        [JsonIgnore] public virtual DbSet<KpiWeightage> KpiWeightages { get; set; }
    }
}
