//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biit_Employee_Performance_Apraisal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeerEvaluation
    {
        public int evaluator_id { get; set; }
        public int evaluatee_id { get; set; }
        public int question_id { get; set; }
        public int course_id { get; set; }
        public int session_id { get; set; }
        public int score { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Evaluator Evaluator { get; set; }
        public virtual Questionaire Questionaire { get; set; }
    }
}
