//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biit_Employee_Performance_Apraisal_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public int assigned_to_id { get; set; }
        public int assigned_by_id { get; set; }
        public string task_description { get; set; }
        public int status { get; set; }
        public int weightage { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<System.DateTime> assigned_date { get; set; }
        public Nullable<int> session_id { get; set; }
    
        [JsonIgnore] public virtual Employee Employee { get; set; }
        [JsonIgnore] public virtual Employee Employee1 { get; set; }
        [JsonIgnore] public virtual Session Session { get; set; }
    }
}
